/*
# This C config file is converted from DPO_RT5572_LinuxSTA_2.6.1.3_20121022/RT2870STA.dat
# This file is a binary file and will be read on loading rt.o module.
#
# Modify settings according to your need.
# 
# 1.) set NetworkType to "Adhoc" for using Adhoc-mode, otherwise using Infrastructure
# 2.) set Channel to "0" for auto-select on Infrastructure mode
# 3.) set SSID for connecting to your Accss-point.
# 4.) AuthMode can be "WEPAUTO", "OPEN", "SHARED", "WPAPSK", "WPA2PSK", "WPANONE"
# 5.) EncrypType can be "NONE", "WEP", "TKIP", "AES"
# for more information refer to the DPO_RT5572_LinuxSTA_2.6.1.3_20121022/README_STA_usb.
*/

#define LF "\n"
static const unsigned char RT2870STA_dat[] = {
"#The word of \"Default\" must not be removed"
LF"Default"
LF"CountryRegion=5"
LF"CountryRegionABand=7"
LF"CountryCode="
LF"ChannelGeography=1"
LF"NetworkType=Infra"
LF"WirelessMode=5"
LF"Channel=0"
LF"BeaconPeriod=100"
LF"TxPower=100" 
LF"BGProtection=0"
LF"TxPreamble=0"
LF"RTSThreshold=2347"
LF"FragThreshold=2346"
LF"TxBurst=1"
LF"PktAggregate=0"
LF"WmmCapable=1"
LF"AckPolicy=0;0;0;0"
    
LF"SSID=mytest"
LF"AuthMode=WPA2PSK"
LF"EncrypType=AES"
LF"WPAPSK=12345678"

LF"DefaultKeyID=1"
LF"Key1Type=0"
LF"Key1Str="
LF"Key2Type=0"
LF"Key2Str="
LF"Key3Type=0"
LF"Key3Str="
LF"Key4Type=0"
LF"Key4Str="
LF"PSMode=CAM"
LF"AutoRoaming=0"
LF"RoamThreshold=70"
LF"APSDCapable=0"
LF"APSDAC=0;0;0;0"
LF"HT_RDG=1"
LF"HT_EXTCHA=0"
LF"HT_OpMode=0"
LF"HT_MpduDensity=4"
LF"HT_BW=1"
LF"HT_BADecline=0"
LF"HT_AutoBA=1"
LF"HT_AMSDU=0"
LF"HT_BAWinSize=64"
LF"HT_GI=1"
LF"HT_MCS=33"
LF"HT_MIMOPSMode=3"
LF"HT_DisallowTKIP=1"
LF"HT_STBC=0"
LF"EthConvertMode="
LF"EthCloneMac="
LF"IEEE80211H=0"
LF"TGnWifiTest=0"
LF"WirelessEvent=1"
LF"MeshId=MESH"
LF"MeshAutoLink=1"
LF"MeshAuthMode=OPEN"
LF"MeshEncrypType=NONE"
LF"MeshWPAKEY="
LF"MeshDefaultkey=1"
LF"MeshWEPKEY="
LF"CarrierDetect=0"
LF"AntDiversity=0"
LF"BeaconLostTime=4"
LF"FtSupport=0"
LF"Wapiifname=ra0"
LF"WapiPsk="
LF"WapiPskType="
LF"WapiUserCertPath="
LF"WapiAsCertPath="
LF"PSP_XLINK_MODE=0"
LF"WscManufacturer="
LF"WscModelName="
LF"WscDeviceName="
LF"WscModelNumber="
LF"WscSerialNumber="
LF"RadioOn=1"
LF"WIDIEnable=0"
LF"P2P_L2SD_SCAN_TOGGLE=8"
LF"Wsc4digitPinCode=0"
LF"P2P_WIDIEnable=0"
LF"PMFMFPC=0"
LF"PMFMFPR=0"
LF"PMFSHA256=0"
LF
};
